apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: api
    name: api
  - port: 9001
    targetPort: console
    name: console
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-service
  replicas: 1
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: bitnami/minio:2022.10.15
        ports:
        - containerPort: 9000
          name: api
        - containerPort: 9001
          name: console
        # command: ["server", "/data", "--console-address", ":9001"]
        env:
          - name: MINIO_ROOT_USER
            value: minio
          - name: MINIO_ROOT_PASSWORD
            value: minio123
        volumeMounts:
        - name: minio
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
